-- Working with dates

SELECT NOW() - INTERVAL '10 MONTHS'; -- YEARS

SELECT (NOW() - INTERVAL '9 DAYS')::DATE;

-- Analog
SELECT EXTRACT(YEAR FROM NOW());

SELECT EXTRACT(DAY FROM NOW());

-- Day of week
SELECT EXTRACT(DOW FROM NOW());

SELECT EXTRACT(CENTURY FROM NOW());
